# --- Tmux Configuration ---

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to copy (yank) to macOS system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Update default binding of 'Enter' to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Bind 'MouseDragEnd1Pane' to copy to clipboard immediately after mouse selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Enable mouse mode
set -g mouse on

# Bind 'Prefix + p' to paste from macOS clipboard
bind p run "pbpaste | tmux load-buffer - && tmux paste-buffer"
