# Setup local dev env
# Run: brew bundle
#
# NOTE: The cross-platform common core (git, gh, jq, vim, tmux, htop, ncdu,
#       shellcheck, gnupg, corkscrew, cmake, protobuf, zstd, coreutils, etc.)
#       now lives in opt/profiles/packages.tsv and is installed by `pkg-install`
#       (pkg-install-brew on macOS). This Brewfile holds only macOS-specific
#       extras: work tools, GUI casks, taps, and build libraries.
# Helpers
tap 'github/bootstrap'
tap 'nektos/tap'
tap 'hashicorp/tap'

# for cortext
brew 'podman'

cask 'claude-code'

# skipping install docker, lets do this manually
brew 'amazon-ecs-cli'
brew 'asciidoc'
brew 'docbook'
brew 'gdbm'
brew 'lastpass-cli'
brew 'libassuan'
brew 'libgpg-error'
brew 'libyaml'
brew 'oniguruma'
brew 'openssl'
brew 'perl'
brew 'pinentry'
# brew 'python@2'
brew 'readline'
brew 'sqlite'
brew 'sops'
# for node manager
brew 'nvm'
# act tool https://github.com/nektos/act
# brew 'nektos/tap/act'
brew 'rbenv'

# bazel
brew 'buildifier'
brew 'bazelisk'
# brew 'protoc-gen-go'
# brew 'protoc-gen-go-grpc'
# brew 'mockery'

# cask "docker"
cask 'gpg-suite'
brew 'azure-cli'

brew 'goenv'
# golang replaced by goenv: https://github.com/go-nv/goenv/blob/master/INSTALL.md
# brew 'golang'

# install pythons
# for example install another python with : pyenv install 3.9.14
# to set it as the default use the command : pyenv global 3.9.14
# to setup in bash profile: eval "$(pyenv init -)"
brew 'pyenv'

# setup vault (managed via vault-setup.sh)
# brew 'hashicorp/tap/vault'
brew 'kubeconform'
brew 'jsonnet'
brew 'fx'

# snowflake tools
# brew '1password-cli' # had to install manually

cask 'snowflake-snowsql'
brew 'lcov'
brew 'just'
brew 'clang-format'
brew 'opa'
brew 'azure-cli'
brew 'grpcui'
brew 'grpcurl'
brew 'kind'
brew 'awscli'

# https://github.com/snowflakedb/image-advisor
# Requires private tap access: brew tap snowflakedb/prodsec git@github.com:snowflakedb/homebrew-prodsec.git
# Uncomment if you have SSH access to the private tap:
# tap 'snowflake-eng/homebrew-prodsec'
# brew 'image-advisor'

# brew 'bufbuild/buf/buf'

# tap 'snowflake-eng/homebrew-cloudeng'
# brew 'snowflake-eng/homebrew-cloudeng/sanssh'

# TODO: disable, it's no longer working
# tap 'snowflake-eng/fuse'
# brew 'snowflake-eng/fuse/fuse-secret'

# AGM - https://snowflakecomputing.atlassian.net/wiki/spaces/SF/pages/4643880982/AGM+User+Guide+and+FAQ
# tap 'snowflake-eng/homebrew-prodsec'
# brew 'snowflake-eng/homebrew-prodsec/access-group-manager'

# dns stuff
brew 'zns'

# jira stuff - https://github.com/ankitpokhrel/jira-cli?tab=readme-ov-file
brew 'jira-cli'
brew 'gemini-cli'
