# Setup local dev env
# Run: brew bundle
# Helpers
tap 'github/bootstrap'
tap 'nektos/tap'

# skipping install docker, lets do this manually
brew 'amazon-ecs-cli'
brew 'asciidoc'
brew 'bash-completion'
brew 'cmake'
brew 'coreutils'
brew 'corkscrew'
brew 'docbook'
brew 'gdbm'
brew 'htop'
brew 'lastpass-cli'
brew 'libassuan'
brew 'libgpg-error'
brew 'libyaml'
brew 'ncdu'         # disk usage tool
brew 'oniguruma'
brew 'openssl'
brew 'perl'
brew 'pinentry'
brew 'pkg-config'
# brew 'python@2'
brew 'readline'
brew 'shellcheck'
brew 'sqlite'
brew 'vim'
brew 'watch'
# for node manager
brew 'nvm'
# act tool https://github.com/nektos/act
# brew 'nektos/tap/act'
brew 'rbenv'
brew 'git'
brew 'git-lfs'
brew 'gh'

# bazel
brew 'buildifier'
brew 'bazelisk'
# brew 'protoc-gen-go'
# brew 'protoc-gen-go-grpc'
# brew 'mockery'

# cask "docker"
cask 'gpg-suite'
brew 'azure-cli'

brew 'gnupg'
brew 'goenv'
# golang replaced by goenv: https://github.com/go-nv/goenv/blob/master/INSTALL.md
# brew 'golang'

# install pythons
# for example install another python with : pyenv install 3.9.14
# to set it as the default use the command : pyenv global 3.9.14
# to setup in bash profile: eval "$(pyenv init -)"
brew 'pyenv'

# setup vault
brew 'vault'
brew 'kubeconform'
brew 'jsonnet'
brew 'jq'
brew 'zstd'

# snowflake tools
# brew '1password-cli' # had to install manually

cask 'snowflake-snowsql'
brew 'coreutils'
brew 'lcov'
brew 'just'
brew 'clang-format'
brew 'opa'
brew 'azure-cli'
brew 'grpcui'
brew 'grpcurl'
brew 'kind'
brew 'awscli'

# https://github.com/snowflakedb/image-advisor
# brew tap snowflakedb/prodsec git@github.com:snowflakedb/homebrew-prodsec.git
tap 'snowflakedb/homebrew-prodsec'
brew 'image-advisor'

brew 'bufbuild/buf/buf'

tap 'snowflakedb/homebrew-cloudeng'
brew 'snowflakedb/homebrew-cloudeng/sanssh'
