#!/usr/bin/env bash
# gen-index.sh — regenerate all routing/discoverability artifacts from the ai/teams
# source of truth (teams.yaml + persona frontmatter). Deterministic & idempotent.
#
# Generates (all committed to the repo, refreshed on demand / in CI):
#   ai/teams/INDEX.md                 routing index (teams + squads)
#   ai/teams/AGENTS.md (+CLAUDE.md)    root nav
#   ai/teams/<team>/AGENTS.md (+CLAUDE.md)  per-team nav
#   ai/claude/commands/team.md         /team slash command (Claude), table embedded
#   ai/skills/team/SKILL.md            team-routing skill (Antigravity + Claude via sync-skills)
#
# CI runs this and asserts `git diff --exit-code` on these paths (must be committed).
set -euo pipefail

TEAMS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${TEAMS_DIR}/../.." && pwd)"
TEAMS_YAML="${TEAMS_DIR}/teams.yaml"
GEN="<!-- GENERATED by ai/teams/gen-index.sh — do not edit by hand. Regenerate: bash ai/teams/gen-index.sh -->"

command -v yq >/dev/null 2>&1 || { echo "gen-index: yq required" >&2; exit 1; }

fm_end() { grep -n '^---[[:space:]]*$' "$1" | sed -n '2p' | cut -d: -f1; }
fmq() { local e; e="$(fm_end "$1")"; sed -n "2,$((e-1))p" "$1" | yq "$2"; }

teams() { yq '.teams | keys | .[]' "$TEAMS_YAML"; }
team_meta() { yq ".teams.\"$1\".$2" "$TEAMS_YAML"; }
# persona files for a team, sorted by role
team_personas() { find "${TEAMS_DIR}/$1" -maxdepth 1 -name 'the_*.md' | sort; }

# ---- INDEX.md -------------------------------------------------------------------------
gen_index() {
  local out="${TEAMS_DIR}/INDEX.md" t sym disp f role tier dom uw aw
  {
    echo "# AI Teams — Routing Index"
    echo
    echo "$GEN"
    echo
    echo "Two-level routing: pick a **team** by domain/keywords, then a **member** by role."
    echo "Installed agents are invoked as \`@agent-<team>-<role>\` (Claude) / \`<team>-<role>\` (Antigravity)"
    echo "/ \`teams-<team>-<role>\` (Ollama). Run \`/team <team|squad>\` to surface a curated set."
    echo
    echo "## Teams"
    while IFS= read -r t; do
      [ -n "$t" ] || continue
      sym="$(team_meta "$t" symbol)"; disp="$(team_meta "$t" display)"
      echo
      echo "### ${sym} ${t} — ${disp}"
      echo
      echo "| member | invoke | tier | use when | avoid |"
      echo "|--------|--------|------|----------|-------|"
      while IFS= read -r f; do
        [ -e "$f" ] || continue
        role="$(fmq "$f" '.role')"; tier="$(fmq "$f" '.tier')"
        dom="$(fmq "$f" '.use_when')"; aw="$(fmq "$f" '.avoid_when')"
        echo "| ${role} | \`${t}-${role}\` | ${tier} | ${dom} | ${aw} |"
      done < <(team_personas "$t")
    done < <(teams)
    echo
    echo "## Squads (cross-team)"
    echo
    echo "| squad | members | when |"
    echo "|-------|---------|------|"
    while IFS= read -r sq; do
      [ -n "$sq" ] || continue
      local members desc
      members="$(yq ".squads.\"$sq\".members | join(\", \")" "$TEAMS_YAML")"
      desc="$(yq ".squads.\"$sq\".description" "$TEAMS_YAML")"
      echo "| \`${sq}\` | ${members} | ${desc} |"
    done < <(yq '.squads | keys | .[]' "$TEAMS_YAML")
  } > "$out"
  echo "  wrote ai/teams/INDEX.md"
}

# ---- per-team + root AGENTS.md (+ CLAUDE.md symlinks) ---------------------------------
gen_nav() {
  local t sym disp f role tier dom
  # root
  {
    echo "# AI Teams"
    echo
    echo "$GEN"
    echo
    echo "Specialized agent teams, installed as native subagents for Claude,"
    echo "Antigravity, and Ollama by \`opt/scripts/system/install_ai_teams.sh\`. Personas live"
    echo "in \`<team>/the_*.md\` (YAML frontmatter + body); an abstract \`tier:\` is resolved to"
    echo "concrete models via [model-map.yaml](./model-map.yaml). Registry + cross-team squads:"
    echo "[teams.yaml](./teams.yaml). Full routing table: [INDEX.md](./INDEX.md)."
    echo
    echo "| team | members | tier mix |"
    echo "|------|---------|----------|"
    while IFS= read -r t; do
      [ -n "$t" ] || continue
      sym="$(team_meta "$t" symbol)"; disp="$(team_meta "$t" display)"
      local roles; roles="$(team_personas "$t" | while IFS= read -r f; do fmq "$f" '.role'; done | paste -sd', ' -)"
      echo "| ${sym} [${t}](./${t}/) — ${disp} | ${roles} | $(team_meta "$t" default_tier) |"
    done < <(teams)
  } > "${TEAMS_DIR}/AGENTS.md"
  ln -sf AGENTS.md "${TEAMS_DIR}/CLAUDE.md"

  # per team
  while IFS= read -r t; do
    [ -n "$t" ] || continue
    sym="$(team_meta "$t" symbol)"; disp="$(team_meta "$t" display)"
    {
      echo "# ${sym} ${disp} (${t})"
      echo
      echo "$GEN"
      echo
      echo "Members of the **${t}** team. See [../INDEX.md](../INDEX.md) for full routing + squads."
      echo
      echo "| member | invoke | tier | owns |"
      echo "|--------|--------|------|------|"
      while IFS= read -r f; do
        [ -e "$f" ] || continue
        role="$(fmq "$f" '.role')"; tier="$(fmq "$f" '.tier')"; dom="$(fmq "$f" '.domain')"
        echo "| ${role} | \`${t}-${role}\` | ${tier} | ${dom} |"
      done < <(team_personas "$t")
    } > "${TEAMS_DIR}/${t}/AGENTS.md"
    ln -sf AGENTS.md "${TEAMS_DIR}/${t}/CLAUDE.md"
  done < <(teams)
  echo "  wrote root + per-team AGENTS.md (+ CLAUDE.md symlinks)"
}

# ---- /team command (claude .md) + team skill (shared), routing table embedded ---------
# Build a compact team→member table reused by both commands.
compact_table() {
  local t f role uw
  while IFS= read -r t; do
    [ -n "$t" ] || continue
    while IFS= read -r f; do
      [ -e "$f" ] || continue
      role="$(fmq "$f" '.role')"; uw="$(fmq "$f" '.use_when')"
      echo "- ${t}-${role}: ${uw}"
    done < <(team_personas "$t")
  done < <(teams)
}
compact_squads() {
  local sq members
  while IFS= read -r sq; do
    [ -n "$sq" ] || continue
    members="$(yq ".squads.\"$sq\".members | join(\", \")" "$TEAMS_YAML")"
    echo "- ${sq}: ${members}"
  done < <(yq '.squads | keys | .[]' "$TEAMS_YAML")
}

gen_command() {
  local tbl sqd
  tbl="$(compact_table)"
  sqd="$(compact_squads)"
  mkdir -p "${REPO}/ai/claude/commands" "${REPO}/ai/skills/team"

  # Claude slash command
  {
    echo "---"
    echo "description: Route a task to the right AI team + member (two-level team→member selection)"
    echo "---"
    echo
    echo "You are routing a development task to the best-fit specialist agent from the AI teams."
    echo
    echo "Task / argument: \$ARGUMENTS"
    echo
    echo "If the argument names a **squad**, recommend that squad's members. If it names a **team**,"
    echo "list that team's members. Otherwise infer the team from the task (file types, domain,"
    echo "keywords), then pick the single best member — and a squad if the task spans teams."
    echo "Invoke a member with \`@agent-<team>-<role>\`. Prefer the most specific member; do not"
    echo "fan out the whole team. Explain the choice in one line."
    echo
    echo "### Members (team-role: use when)"
    echo "$tbl"
    echo
    echo "### Squads (cross-team)"
    echo "$sqd"
  } > "${REPO}/ai/claude/commands/team.md"

  # Shared team-routing skill (SKILL.md). Discovered by Antigravity CLI
  # (~/.gemini/config/skills via sync-skills.sh) and Claude Code
  # (~/.claude/skills); replaces the retired Gemini CLI /team TOML command.
  {
    echo "---"
    echo "name: team"
    echo "description: Route a task to the right AI team + member (two-level team→member selection)"
    echo "---"
    echo
    echo "$GEN"
    echo
    echo "Route a development task to the best-fit specialist agent from the AI teams."
    echo
    echo "If the request names a **squad**, recommend that squad's members. If it names a **team**,"
    echo "list that team's members. Otherwise infer the team from the task (file types, domain,"
    echo "keywords), then pick the single best member — and a squad if the task spans teams."
    echo "Invoke a member with \`@agent-<team>-<role>\` (Claude) / \`<team>-<role>\` (Antigravity)."
    echo "Prefer the most specific member; do not fan out the whole team. Explain the choice in"
    echo "one line."
    echo
    echo "### Members (team-role: use when)"
    echo "$tbl"
    echo
    echo "### Squads (cross-team)"
    echo "$sqd"
  } > "${REPO}/ai/skills/team/SKILL.md"
  echo "  wrote ai/claude/commands/team.md + ai/skills/team/SKILL.md"
}

echo "Regenerating ai/teams routing artifacts..."
gen_index
gen_nav
gen_command
echo "Done."
