name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
# a dind example
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag wenlock/dotfiles:latest .
      run: docker run --privileged wenlock/dotfiles:latest docker build --tag test opt/docker/helloworld
